# Generated by Django 4.0.4 on 2022-05-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlaform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='discription',
            new_name='story_line',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.streamingplaform'),
            preserve_default=False,
        ),
    ]
